<a href="https://colab.research.google.com/github/SiddheshDaphane/Deep_Learning_With_PyTorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu121


## Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [7]:
vector.shape

torch.Size([3])

In [8]:
vector.ndim

1

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8,9],
                       [10,11,12]])
MATRIX

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]]])

In [13]:
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 4])

In [16]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],
                       [[11,22,33,44],
                       [55,66,77,88],
                       [99,111,222,333]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 3, 4])

## Random Tensor

In [19]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1920, 0.1235, 0.5966, 0.2333],
         [0.7528, 0.3572, 0.3901, 0.7137],
         [0.0073, 0.2419, 0.4136, 0.6589]]),
 torch.float32)

In [20]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # Height, width, color_channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range and tensors like

In [23]:
zero_to_ten_deprecated = torch.range(0,10)
zero_to_ten_deprecated

<ipython-input-23-bb89a8424578>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ten_zeros.ndim

1

In [27]:
ten_zeros.shape

torch.Size([10])

## Tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # defaults to none, which is torch.float32 or whatever datatype is passed
                               device=None, # defaluts to None, which uses the default tensor type
                               requires_grad=False) # if true, operations performed on the tensor are recorded.
float_32_tensor.shape

torch.Size([3])

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

## Tensor Manipulating (tensor operations)

In [2]:
import torch

In [8]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [4]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [5]:
tensor # original value doesn't change unless you assigned it.

tensor([1, 2, 3])

In [9]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [10]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [11]:
# Can use built-in function also
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [12]:
tensor # still unchanged.

tensor([1, 2, 3])

In [13]:
tensor * tensor

tensor([1, 4, 9])

## Matrix multiplication (VIMP)

The main two rules for matrix muktiplication are:

1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> (2,2)
* `(3,2) @ (2,3)` -> (3,3)

*External Links*

1) https://www.mathsisfun.com/algebra/matrix-multiplying.html

2) http://matrixmultiplication.xyz/

In [14]:
tensor = torch.tensor([1,2,3])
tensor, tensor.shape

(tensor([1, 2, 3]), torch.Size([3]))