<a href="https://colab.research.google.com/github/SiddheshDaphane/Deep_Learning_With_PyTorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu121


## Creating Tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [8]:
vector.shape

torch.Size([3])

In [9]:
vector.ndim

1

In [13]:
# Matrix
MATRIX = torch.tensor([[7,8,9],
                       [10,11,12]])
MATRIX

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 3])

In [16]:
# Tensor
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]]])

In [17]:
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 4])

In [23]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],
                       [[11,22,33,44],
                       [55,66,77,88],
                       [99,111,222,333]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([2, 3, 4])