<a href="https://colab.research.google.com/github/SiddheshDaphane/Deep_Learning_With_PyTorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu121


## Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [7]:
vector.shape

torch.Size([3])

In [8]:
vector.ndim

1

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8,9],
                       [10,11,12]])
MATRIX

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]]])

In [13]:
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 4])

In [16]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],
                       [[11,22,33,44],
                       [55,66,77,88],
                       [99,111,222,333]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 3, 4])

## Random Tensor

In [19]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1920, 0.1235, 0.5966, 0.2333],
         [0.7528, 0.3572, 0.3901, 0.7137],
         [0.0073, 0.2419, 0.4136, 0.6589]]),
 torch.float32)

In [20]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # Height, width, color_channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range and tensors like

In [23]:
zero_to_ten_deprecated = torch.range(0,10)
zero_to_ten_deprecated

<ipython-input-23-bb89a8424578>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ten_zeros.ndim

1

In [27]:
ten_zeros.shape

torch.Size([10])

## Tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # defaults to none, which is torch.float32 or whatever datatype is passed
                               device=None, # defaluts to None, which uses the default tensor type
                               requires_grad=False) # if true, operations performed on the tensor are recorded.
float_32_tensor.shape

torch.Size([3])

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

## Tensor Manipulating (tensor operations)

In [2]:
import torch

In [8]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [4]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [5]:
tensor # original value doesn't change unless you assigned it.

tensor([1, 2, 3])

In [9]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [10]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [11]:
# Can use built-in function also
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [12]:
tensor # still unchanged.

tensor([1, 2, 3])

In [13]:
tensor * tensor

tensor([1, 4, 9])

## Matrix multiplication (VIMP)

The main two rules for matrix muktiplication are:

1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> (2,2)
* `(3,2) @ (2,3)` -> (3,3)

*External Links*

1) https://www.mathsisfun.com/algebra/matrix-multiplying.html

2) http://matrixmultiplication.xyz/

In [14]:
tensor = torch.tensor([1,2,3])
tensor, tensor.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [16]:
tensor

tensor([1, 2, 3])

In [15]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [17]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [18]:
tensor @ tensor

tensor(14)

#### One of the most common errors in deep learning is shape error which basically violation of 1st rule of matrix multiplication

In [19]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [20]:
tensor_A , tensor_B

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [22]:
torch.matmul(tensor_A,tensor_B) # cannot multiply (3,2) and (3,2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [23]:
# Let's transpose to make it possible
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [24]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [25]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (aggregation)

In [26]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
x.min()

tensor(0)

In [28]:
x.max()

tensor(90)

In [30]:
x.mean() # to use `mean`, tensor should be in torch.float32 datatype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [31]:
x.type(torch.float32).mean()

tensor(45.)

In [32]:
x.sum()

tensor(450)

### Positional min/max

In [33]:
x.argmin()

tensor(0)

In [34]:
x.argmax()

tensor(9)

In [35]:
x[9]

tensor(90)

### Change tensor datatype

In [37]:
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [38]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [39]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing,unsqueezing and permute

In [40]:
import torch

In [41]:
x = torch.arange(1.,8.)

In [42]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

#### reshape

In [43]:
x_reshaped = x.reshape(1,7)

In [46]:
x_reshaped , x_reshaped.shape # We added extra dimension with torch.reshape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

#### view

In [48]:
# torch.view(). View shares the memory with original tensor which means any changes in the view, original tensor will also change

z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [49]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

#### Stack

In [52]:
x_stacked = torch.stack([x,x*2,x*4,x*6], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.],
        [10.,  4.,  6.,  8., 10., 12., 14.],
        [20.,  8., 12., 16., 20., 24., 28.],
        [30., 12., 18., 24., 30., 36., 42.]])

#### Squeeze

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


#### Unsqueeze

In [56]:
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


#### Permute

In [57]:
# Create a tensor with specific shape
x_original = torch.rand(224,224,3)

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1) # shifts axis 0 -> 1, 1 -> 2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [58]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [59]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
x[0][0]

tensor([1, 2, 3])

In [61]:
x[0][0][0]

tensor(1)

In [62]:
x[:,0]

tensor([[1, 2, 3]])

In [63]:
x[:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [64]:
x[:,:,0]

tensor([[1, 4, 7]])

In [65]:
x[:,0,1]

tensor([2])

### PyTorch tensors & NumPy

* `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor

* `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array

By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).



In [66]:
import torch
import numpy as np

In [67]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [68]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [70]:
array = array + 10
array, tensor # changes in array will not change the tensor meaning it doesn't share a memory

(array([21., 22., 23., 24., 25., 26., 27.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
tensor = torch.arange(1.,5.)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # look at the datatype of the array

(tensor([1., 2., 3., 4.]), array([1., 2., 3., 4.], dtype=float32))

### Reproducibility

In [74]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPUs

In [1]:
!nvidia-smi

Tue Dec 17 17:49:50 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### PyTorch on Apple Silicon

In [5]:
torch.backends.mps.is_available()

False

### Putting tensors (and models) on the GPU

In [7]:
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if aviavlable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [10]:
tensor_on_gpu.numpy() # error because numpy doesn't run on GPU

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

above returns a copy of GPU tensor in CPU memory so the original tensor is still on GPU

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')